apiVersion: batch/v1
kind: CronJob
metadata:
    name: clean.dangling-images
spec:
    schedule: "30 03 * * *" # every day in the middle of the night (3h30)
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        app: cron-task
                spec:
                    containers:
                        - name: gc-dangling-images
                          image: jfvoliveira2001/scc2022-functions:v2
                          imagePullPolicy: Always
                          args: [ GCDanglingImages ]
                          env:
                              - name: DB_CONNSTRING
                                value: "mongodb://root:root@mongo:27017/"
                              - name: DB_NAME
                                value: scc2022-project-db
                              - name: BLOBSTORE_CONNSTRING
                                value: /var/blobstore
                          volumeMounts:
                              - mountPath: /var/blobstore
                                name: blob-store-volume
                          resources:
                              requests:
                                  cpu: 100m
                                  memory: 500Mi
                              limits:
                                  cpu: 300m
                                  memory: 750Mi
                    volumes:
                        -   name: blob-store-volume
                            persistentVolumeClaim:
                                claimName: image-store
                    restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: clean.remove-users
spec:
    schedule: "*/10 * * * *" # every 10 minutes
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        app: cron-task
                spec:
                    containers:
                        - name: gc-remove-users
                          image: jfvoliveira2001/scc2022-functions:v2
                          imagePullPolicy: Always
                          args: [ GCRemoveUsers ]
                          env:
                              - name: REDIS_HOSTNAME
                                value: redis
                              - name: REDIS_PORT
                                value: "6379"
                              - name: DB_CONNSTRING
                                value: "mongodb://root:root@mongo:27017/"
                              - name: DB_NAME
                                value: scc2022-project-db
                          resources:
                              requests:
                                  cpu: 100m
                                  memory: 500Mi
                              limits:
                                  cpu: 300m
                                  memory: 750Mi
                    restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: clean.close-auctions
spec:
    schedule: "*/2 * * * *" # every two minutes
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        app: cron-task
                spec:
                    containers:
                        - name: auction-closer
                          image: jfvoliveira2001/scc2022-functions:v2
                          imagePullPolicy: Always
                          args: [ CloseAuctions ]
                          env:
                              - name: DB_CONNSTRING
                                value: "mongodb://root:root@mongo:27017/"
                              - name: DB_NAME
                                value: scc2022-project-db
                          resources:
                              requests:
                                  cpu: 100m
                                  memory: 500Mi
                              limits:
                                  cpu: 300m
                                  memory: 750Mi
                    volumes:
                        -   name: blob-store-volume
                            persistentVolumeClaim:
                                claimName: image-store
                    restartPolicy: OnFailure