apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: image-store
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: azurefile
    resources:
        requests:
            storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-mount
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi