# volume claim for web-app image store
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: image-store
spec:
    accessModes:
        - ReadWriteMany
    # multiple instances can be active
    storageClassName: azurefile
    resources:
        requests:
            storage: 5Gi
---
# volume claim for mongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-mount
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi